version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"  # Port for AMQP protocol
      - "15672:15672" # Port for RabbitMQ Management UI
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge