# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Python application

on:
  push:
    branches: [ "main" , "jp-dev-hp" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    
    - name: Install dependencies
      run: |
        sudo chmod +x ./init.sh
        ./init.sh
    
    - name: Test with pytest
      env:
        PYTHONPATH: .
      run: |
        source .venv/bin/activate
        pytest tests/ --maxfail=3 --disable-warnings -v
