# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test du service d'Embedding

on:
  push:
    branches: [ "main" , "features/embedding" ]
  pull_request:
    branches: [ "main" , "develop" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Get the code
      uses: actions/checkout@v4
      
    # - name: Cache Python packages
    #   uses: actions/cache@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    
    - name: Install dependencies
      run: |
        cd apps-microservices/embedding-service
        sudo chmod +x ./init.sh
        ./init.sh
    
    - name: Test with pytest
      env:
        PYTHONPATH: .
      run: |
        cd apps-microservices/embedding-service
        source .venv/bin/activate
        pytest tests/ --maxfail=3 --disable-warnings -v
